services:
  db:
      image: postgres:16-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=BackPoloIT
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 1m30s
        timeout: 30s
        retries: 5
        start_period: 30s
      volumes:
        - pgdata:/var/lib/postgresql/data
      expose:
        - 3030
  
  volumes:
    pgdata:
